export const customersData = [
  {
    id: 1,
    firstName: 'Joe',
    lastName: 'Schilder',
    name: 'Joe Schilder',
    email: 'sip@gmail.com',
    age: 39,
    gender: 'Female',
    role: 'Scientific Writer',
    orders: 9603,
    progress: 44,
    status: 3,
    orderStatus: 'Dispatched',
    contact: '(731) 342-9783',
    country: 'Canada',
    location: '1631 Melgu Square, Ujdeme, Maldives - 56391',
    fatherName: 'Isaac McGee',
    about: 'Worbov fuggodbe uvawo za rimpewej uc wehele comi buan wam mes gacebu meb fupgop webkem gon enmile.',
    avatar: 8,
    skills: ['Wireframing', 'Figma', 'Web App', 'ES6', 'UX', 'Javascript'],
    time: ['2 days ago'],
    date: '29.07.2023'
  },
  {
    id: 2,
    firstName: 'Phoebe',
    lastName: 'Venturi',
    name: 'Phoebe Venturi',
    email: 'ke@gmail.com',
    age: 52,
    gender: 'Female',
    role: 'Logistics Manager',
    orders: 7174,
    progress: 84,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(887) 744-6950',
    country: 'Thailand',
    location: '1804 Ahedi Trail, Owottug, Bolivia - 47403',
    fatherName: 'Helen Stewart',
    about: 'Udukaape gozune jig fu foslinan tadka kumu no guw upe or cifdasbej di ige.',
    avatar: 8,
    skills: ['React', 'Mobile App', 'Prototyping', 'UX', 'Figma'],
    time: ['1 day ago'],
    date: '14.07.2023'
  },
  {
    id: 3,
    firstName: 'Caroline',
    lastName: 'Pandolfi',
    name: 'Caroline Pandolfi',
    email: 'secjavkib@gmail.com',
    age: 45,
    gender: 'Female',
    role: 'Physicist',
    orders: 2585,
    progress: 16,
    status: 1,
    orderStatus: 'Cancelled',
    contact: '(618) 787-3453',
    country: 'Barbados',
    location: '1060 Ejeaba Square, Wouruno, Congo - Kinshasa - 24456',
    fatherName: 'Herbert Todd',
    about: 'Totug amuovve cakwud amlevat ja gepsi zan bulfivki mij dultej etuuf dakirpe.',
    avatar: 4,
    skills: ['ES6', 'Figma', 'Backend', 'Mobile App', 'Javascript'],
    time: ['1 year ago'],
    date: '10.07.2023'
  },
  {
    id: 4,
    firstName: 'Ricardo',
    lastName: 'Marchetti',
    name: 'Ricardo Marchetti',
    email: 'ho@gmail.com',
    age: 29,
    gender: 'Female',
    role: 'Banker',
    orders: 9283,
    progress: 48,
    status: 1,
    orderStatus: 'Refunded',
    contact: '(415) 628-7505',
    country: 'Italy',
    location: '1614 Fomwaj Square, Eknisra, Iceland - 41340',
    fatherName: 'Gerald Patterson',
    about: 'Riv mi hudgoh esviwoc usojipa vub palbesdu det vies pop rutsenazo viwwij esedakvu novfovih afjoda cimuwiec ebve.',
    avatar: 5,
    skills: ['Codeigniter', 'Wireframing', 'Angular', 'Backend', 'UX', 'UI Design'],
    time: ['1 week ago'],
    date: '2.07.2023'
  },
  {
    id: 5,
    firstName: 'Dorothy',
    lastName: 'Hussain',
    name: 'Dorothy Hussain',
    email: 'socuih@gmail.com',
    age: 58,
    gender: 'Female',
    role: 'International Acct.',
    orders: 4872,
    progress: 26,
    status: 2,
    orderStatus: 'Delivered',
    contact: '(856) 459-8945',
    country: 'Mauritius',
    location: '1397 Morco Path, Gamarib, Malta - 65124',
    fatherName: 'Henrietta Griffin',
    about: 'Avureput etluh iketi vosfo jamow do junabgog biw tovwenil fezpa aneow cizhel.',
    avatar: 6,
    skills: ['Codeigniter', 'Angular', 'UI Design', 'Backend', 'React'],
    time: ['2 days ago'],
    date: '30.06.2023'
  },
  {
    id: 6,
    firstName: 'Eleanor',
    lastName: 'Mann',
    name: 'Eleanor Mann',
    email: 'jonvok@gmail.com',
    age: 60,
    gender: 'Male',
    role: 'Design Engineer',
    orders: 499,
    progress: 8,
    status: 3,
    orderStatus: 'Dispatched',
    contact: '(507) 561-6927',
    country: 'American Samoa',
    location: '25 Odvaz Grove, Nadrubo, Belize - 93095',
    fatherName: 'Dollie Griffin',
    about: 'Ciaj dubeco muzogho bunwe ogtafa nij fizanul nopgoomu wuf hiwop tot ser wefoz uhe anaced.',
    avatar: 2,
    skills: ['Codeigniter', 'Figma'],
    time: ['1 hour ago'],
    date: '22.06.2023'
  },
  {
    id: 7,
    firstName: 'Nina',
    lastName: 'Francini',
    name: 'Nina Francini',
    email: 'uhudadof@gmail.com',
    age: 27,
    gender: 'Male',
    role: 'Aerospace Engineer',
    orders: 3066,
    progress: 73,
    status: 1,
    orderStatus: 'Shipped',
    contact: '(722) 952-7792',
    country: 'Gibraltar',
    location: '1984 Faza Point, Wakukda, India - 94335',
    fatherName: 'Danny Cohen',
    about: 'Besilija zomka nijiso puadehaz ve pi ecpogapo cotesen ceuje hohih ewuiw bo.',
    avatar: 3,
    skills: ['Angular', 'Javascript', 'React'],
    time: ['1 hour ago'],
    date: '18.06.2023'
  },
  {
    id: 8,
    firstName: 'Caroline',
    lastName: 'Mallet',
    name: 'Caroline Mallet',
    email: 'peg@gmail.com',
    age: 26,
    gender: 'Female',
    role: 'Director',
    orders: 5478,
    progress: 24,
    status: 3,
    orderStatus: 'Processing',
    contact: '(675) 882-6307',
    country: 'Central African Republic',
    location: '725 Zehvo Highway, Puvoef, Japan - 93292',
    fatherName: 'Phoebe Hanson',
    about: 'Asowag me ogetem gir joaw ki cuhug lakvo ujesa volhuj rettu powpa agoku va gajpah kinulov gechubte.',
    avatar: 5,
    skills: ['Web App', 'Prototyping', 'Wireframing'],
    time: ['1 hour ago'],
    date: '5.06.2023'
  },
  {
    id: 9,
    firstName: 'Amy',
    lastName: 'Pratt',
    name: 'Amy Pratt',
    email: 'vavceriji@gmail.com',
    age: 47,
    gender: 'Female',
    role: 'Urban Planner',
    orders: 6255,
    progress: 6,
    status: 1,
    orderStatus: 'Refunded',
    contact: '(906) 966-2597',
    country: 'Indonesia',
    location: '333 Hinur Trail, Zepopde, Kiribati - 39279',
    fatherName: 'Harriett Gonzales',
    about: 'Vo icu re da ula kumgajbeg fuhem wuwe doiso uvoege lu ipekocpub.',
    avatar: 3,
    skills: ['Backend', 'UI Design'],
    time: ['5 months ago'],
    date: '31.05.2023'
  },
  {
    id: 10,
    firstName: 'Gene',
    lastName: 'Montero',
    name: 'Gene Montero',
    email: 'rouca@gmail.com',
    age: 55,
    gender: 'Male',
    role: 'Administrator',
    orders: 702,
    progress: 62,
    status: 2,
    orderStatus: 'Delivered',
    contact: '(969) 819-7489',
    country: 'Yemen',
    location: '1409 Ifuwu Trail, Davdibun, Nepal - 22947',
    fatherName: 'Mason Brady',
    about: 'Ro atvawvih somhek nipdoni hotfaltab mujle etajevuj ra pev mi duzahi redka se mab dem rorjeab tel hiwehar.',
    avatar: 4,
    skills: ['Javascript', 'Figma', 'HTML'],
    time: ['1 day ago'],
    date: '13.05.2023'
  },
  {
    id: 11,
    firstName: 'Ollie',
    lastName: 'Barbetti',
    name: 'Ollie Barbetti',
    email: 'bap@gmail.com',
    age: 64,
    gender: 'Female',
    role: 'City Housing Manager',
    orders: 8006,
    progress: 88,
    status: 2,
    orderStatus: 'Dispatched',
    contact: '(323) 498-6272',
    country: 'Central African Republic',
    location: '577 Zeoz Drive, Misoov, Martinique - 29073',
    fatherName: 'Nina Stanley',
    about: 'Igalewuh idpowu tivwi zedro pidfufbic juz ot kor beb wopaeha ughema odi ebwuco ju.',
    avatar: 8,
    skills: ['Javascript', 'Prototyping'],
    time: ['1 year ago'],
    date: '27.04.2023'
  },
  {
    id: 12,
    firstName: 'Katherine',
    lastName: 'Olivier',
    name: 'Katherine Olivier',
    email: 'newe@gmail.com',
    age: 41,
    gender: 'Female',
    role: 'Jeweler',
    orders: 261,
    progress: 68,
    status: 2,
    orderStatus: 'Completed',
    contact: '(740) 673-7034',
    country: 'Nicaragua',
    location: '1563 Kukrez River, Vegotaf, Tristan da Cunha - 54129',
    fatherName: 'Harold Fowler',
    about: 'Gajvaj mam won wo azeovoz mo ki apa bukihroh po lati takobada.',
    avatar: 4,
    skills: ['Figma', 'React'],
    time: ['2 days ago'],
    date: '6.04.2023'
  },
  {
    id: 13,
    firstName: 'Fanny',
    lastName: 'Renault',
    name: 'Fanny Renault',
    email: 'at@gmail.com',
    age: 62,
    gender: 'Male',
    role: 'Communications Engineer',
    orders: 2924,
    progress: 30,
    status: 3,
    orderStatus: 'Shipped',
    contact: '(571) 692-3845',
    country: 'Northern Mariana Islands',
    location: '755 Siar Ridge, Niedme, Sudan - 61803',
    fatherName: 'Harold Goodman',
    about: 'Jiloki uvma vonfovic onu ej upuza ih hitwotmac odowa jicfu sunas gut uk edwaama zehwake lonevwa.',
    avatar: 9,
    skills: ['UI Design', 'Figma', 'Wireframing', 'ES6', 'UX', 'Backend'],
    time: ['1 week ago'],
    date: '20.03.2023'
  },
  {
    id: 14,
    firstName: 'Dean',
    lastName: 'McCarthy',
    name: 'Dean McCarthy',
    email: 'bovli@gmail.com',
    age: 31,
    gender: 'Female',
    role: 'Film Producer',
    orders: 1809,
    progress: 40,
    status: 2,
    orderStatus: 'Refunded',
    contact: '(608) 235-8613',
    country: 'Greenland',
    location: '1609 Esegov Key, Casapop, Kenya - 74802',
    fatherName: 'Susie Fowler',
    about: 'Dad wehut do few rikbihlum favejazat zuwe osowehes elituri me sobgiz mif ci ozmebfi.',
    avatar: 6,
    skills: ['Figma', 'UX', 'Web App', 'React', 'Wireframing'],
    time: ['3 hours ago'],
    date: '03.03.2023'
  },
  {
    id: 15,
    firstName: 'Kyle',
    lastName: 'Papucci',
    name: 'Kyle Papucci',
    email: 'naborga@gmail.com',
    age: 47,
    gender: 'Female',
    role: 'Scientific Writer',
    orders: 7957,
    progress: 66,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(623) 270-6754',
    country: 'Afghanistan',
    location: '155 Lajac Square, Otozicut, Ghana - 99354',
    fatherName: 'Noah Huff',
    about: 'Okaiguki ni hisnunas vem po wi wekha arduglo cantacoh vankurzo sav jisa kiviw sibosot ek jom ercezziw.',
    avatar: 6,
    skills: ['HTML', 'Figma', 'Prototyping', 'Wireframing', 'ES6'],
    time: ['just now'],
    date: '28.02.2023'
  },
  {
    id: 16,
    firstName: 'Clifford',
    lastName: 'Hayes',
    name: 'Clifford Hayes',
    email: 'rempesdel@gmail.com',
    age: 51,
    gender: 'Female',
    role: 'Park Ranger',
    orders: 4636,
    progress: 92,
    status: 2,
    orderStatus: 'Processing',
    contact: '(646) 585-1373',
    country: 'Comoros',
    location: '1776 Gide Glen, Fizogeh, Kuwait - 75148',
    fatherName: 'Willie Ward',
    about: 'Ram pujtut mi rik rok ove dim wavzuw awewikoz it dukrawe ojevi uhnujus jaonil.',
    avatar: 10,
    skills: ['Angular', 'Figma', 'Backend', 'UI Design'],
    time: ['2 days ago'],
    date: '19.02.2023'
  },
  {
    id: 17,
    firstName: 'Daisy',
    lastName: 'Andres',
    name: 'Daisy Andres',
    email: 'watjoap@gmail.com',
    age: 35,
    gender: 'Female',
    role: 'Biotechnical Researcher',
    orders: 9852,
    progress: 65,
    status: 3,
    orderStatus: 'Processing',
    contact: '(857) 597-2624',
    country: 'Pitcairn Islands',
    location: '1165 Ifcil Glen, Fejafma, British Indian Ocean Territory - 42333',
    fatherName: 'Willie Stone',
    about: 'Owanih ilevgi eja huz waipi kufe wi he muvir ogurasu zos bibtuw aj ge zi peadoc jeckibu.',
    avatar: 3,
    skills: ['ES6', 'HTML'],
    time: ['2 min ago'],
    date: '2.02.2023'
  },
  {
    id: 18,
    firstName: 'Ronald',
    lastName: 'Bentley',
    name: 'Ronald Bentley',
    email: 'pi@gmail.com',
    age: 42,
    gender: 'Male',
    role: 'Baker',
    orders: 1125,
    progress: 18,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(881) 700-1479',
    country: 'Japan',
    location: '1333 Faed River, Gonvison, Bahrain - 01190',
    fatherName: 'Rosetta Robbins',
    about: 'Zopescoh usawehfo erutu wicitu izokudro ivpuzup laer time mos ke poebotu wuovito.',
    avatar: 8,
    skills: ['Prototyping', 'Javascript', 'UX', 'Codeigniter', 'Web App'],
    time: ['1 day ago'],
    date: '27.01.2023'
  },
  {
    id: 19,
    firstName: 'Warren',
    lastName: 'Ridolfi',
    name: 'Warren Ridolfi',
    email: 'irlizih@gmail.com',
    age: 38,
    gender: 'Female',
    role: 'Investment Manager',
    orders: 9887,
    progress: 96,
    status: 3,
    orderStatus: 2,
    contact: '(624) 971-8666',
    country: 'Martinique',
    location: '801 Havul Heights, Ratudu, Lithuania - 24321',
    fatherName: 'Christian Peters',
    about: 'Gih juintak zupiko abe funefeg isoze buwaj ifiuvupi zu daditcak uji irute loj.',
    avatar: 3,
    skills: ['UX', 'Web App', 'UI Design', 'Javascript', 'Figma'],
    time: ['1 hour ago'],
    date: '14.01.2023'
  },
  {
    id: 20,
    firstName: 'Cecelia',
    lastName: 'Le GallGall',
    name: 'Cecelia Le GallGall',
    email: 'bonnollol@gmail.com',
    age: 47,
    gender: 'Male',
    role: 'Chemical Engineer',
    orders: 1421,
    progress: 30,
    status: 2,
    orderStatus: 'Completed',
    contact: '(407) 444-2699',
    country: 'Laos',
    location: '717 Evdi Junction, Usehodwar, Mauritius - 90065',
    fatherName: 'Elizabeth McGuire',
    about: 'Dusogov muk uzuebgig huwpubem to dihov azvewo ovo uwkuuk dejpik tized ra tezku.',
    avatar: 1,
    skills: ['Javascript', 'Mobile App'],
    time: ['2 min ago'],
    date: '7.01.2023'
  },
  {
    id: 21,
    firstName: 'Bessie',
    lastName: 'James',
    name: 'Bessie James',
    email: 'obi@gmail.com',
    age: 28,
    gender: 'Female',
    role: 'Horticulturist',
    orders: 4005,
    progress: 96,
    status: 3,
    orderStatus: 2,
    contact: '(668) 801-3695',
    country: 'St. Helena',
    location: '828 Igake Pass, Ebojiire, French Polynesia - 75187',
    fatherName: 'Dale Wolfe',
    about: 'Nagfivmah fepuj wum unfo zodpuc tapjus kemitunat vacve inicug nujvezti va ku ni nos.',
    avatar: 3,
    skills: ['Web App', 'UI Design'],
    time: ['3 hours ago'],
    date: '31.12.2022'
  },
  {
    id: 22,
    firstName: 'Andrew',
    lastName: 'Brown',
    name: 'Andrew Brown',
    email: 'big@gmail.com',
    age: 62,
    gender: 'Female',
    role: 'Preschool Management',
    orders: 1119,
    progress: 73,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(379) 241-7855',
    country: 'Azerbaijan',
    location: '256 Hajuv Grove, Ubrapwaj, Oman - 95099',
    fatherName: 'Barbara Arnold',
    about: 'Suscagu hogutol mici fatgi turkizij vavbinci pihin iwiz zu abhow coihugo ledozi sulga.',
    avatar: 4,
    skills: ['HTML', 'Web App', 'Wireframing', 'Javascript', 'React', 'Codeigniter'],
    time: ['5 months ago'],
    date: '10.12.2022'
  },
  {
    id: 23,
    firstName: 'Curtis',
    lastName: 'Lazzeri',
    name: 'Curtis Lazzeri',
    email: 'ivgukon@gmail.com',
    age: 47,
    gender: 'Female',
    role: 'Sales Engineer',
    orders: 1393,
    progress: 6,
    status: 2,
    orderStatus: 'Processing',
    contact: '(465) 759-3060',
    country: 'Macau SAR China',
    location: '823 Ubtav River, Gegohsi, American Samoa - 22889',
    fatherName: 'Ralph Delgado',
    about: 'Zoljuf jenpap lirbemuf nerak luwuri cohsa hucu do imo giczovo win logaw sejev dazwut fabitjim tadketwa sedo onimepi.',
    avatar: 6,
    skills: ['Codeigniter', 'UX', 'Prototyping', 'Angular', 'Backend'],
    time: ['2 min ago'],
    date: '22.11.2022'
  },
  {
    id: 24,
    firstName: 'Charlie',
    lastName: 'Jensen',
    name: 'Charlie Jensen',
    email: 'ac@gmail.com',
    age: 36,
    gender: 'Female',
    role: 'Broker',
    orders: 4304,
    progress: 80,
    status: 3,
    orderStatus: 'Cancelled',
    contact: '(372) 671-4732',
    country: 'Cayman Islands',
    location: '1380 Mofgo Pass, Palutu, Portugal - 65273',
    fatherName: 'Stephen Patrick',
    about: 'Envem tejonte oli ocjojdet bag bezilfiz celor azaowsa nuzuic jifo gew tiwdoz zuzfefofa gewhigu.',
    avatar: 5,
    skills: ['Backend', 'React'],
    time: ['2 days ago'],
    date: '4.11.2022'
  },
  {
    id: 25,
    firstName: 'Gordon',
    lastName: 'Cummings',
    name: 'Gordon Cummings',
    email: 'pecmu@gmail.com',
    age: 44,
    gender: 'Female',
    role: 'Executive Recruiter',
    orders: 561,
    progress: 27,
    status: 1,
    orderStatus: 'Completed',
    contact: '(201) 535-5050',
    country: 'St. Helena',
    location: '1714 Gevher Drive, Emgawbo, Canada - 26706',
    fatherName: 'Allie Jensen',
    about: 'Ivo udu vekra madih atisidufe vomcilo rejo pepo guidfit tavitifi ebi fobamzak cucuz.',
    avatar: 4,
    skills: ['Prototyping', 'UX', 'Codeigniter', 'HTML', 'Figma'],
    time: ['1 day ago'],
    date: '16.10.2022'
  }
];
