export const technicians = [
  'Alex Johnson',
  'Brooke Simmons',
  'Cameron Lee',
  'Dylan Patel',
  'Evelyn Martinez',
  'Finn Thompson',
  'Grace Clark',
  'Harper Lewis',
  'Isaac White',
  'Jasmine Harris',
  'Kyle Walker',
  'Liam Robinson',
  'Mason Wright',
  'Nora Evans',
  'Oliver Hall',
  'Paige Young',
  'Quinn King',
  'Riley Green',
  'Sophie Turner',
  'Tyler Scott'
];
export const technicianRoles = [
  'Mechanical Engineering Technician',
  'Electrical Engineering Technician',
  'Electronics Technician',
  'HVAC Technician (Heating, Ventilation, and Air Conditioning)',
  'Automotive Technician',
  'Aerospace Technician',
  'Civil Engineering Technician',
  'Industrial Engineering Technician',
  'Quality Control Technician',
  'Robotics Technician',
  'Maintenance Technician',
  'Instrumentation Technician',
  'CNC Technician (Computer Numerical Control)',
  'Telecommunications Technician',
  'Cable Technician',
  'Fiber Optic Technician',
  'RF Technician (Radio Frequency Technician)',
  'Satellite Technician',
  'Automotive Service Technician',
  'Diesel Technician',
  'Aviation Technician',
  'Marine Technician',
  'Motorcycle Technician',
  'Electrical Technician',
  'Wind Turbine Technician',
  'Solar Technician',
  'Power Plant Technician',
  'Gas Technician',
  'Water Treatment Technician',
  'Construction Technician',
  'Elevator Technician',
  'Building Maintenance Technician',
  'Plumbing Technician',
  'Carpentry Technician',
  'Audio/Visual Technician',
  'Broadcast Technician',
  'Sound Technician',
  'Lighting Technician',
  'Stage Technician',
  'Agricultural Technician',
  'Forestry Technician',
  'Environmental Field Technician',
  'Horticulture Technician',
  'Veterinary Technician',
  'Pest Control Technician',
  'Crime Scene Technician',
  'Nail Technician',
  'Esthetician Technician',
  'IT Support Technician',
  'Network Technician',
  'Help Desk Technician',
  'System Technician',
  'Hardware Technician',
  'Field Service Technician',
  'Data Center Technician',
  'Cybersecurity Technician'
];
export const categories = [
  {
    id: 1,
    name: 'Electronics',
    subcategories: [
      'Mobile Phones',
      'Laptops',
      'Headphones',
      'Cameras',
      'Smartwatches',
      'Televisions',
      'Home Audio',
      'Wearable Technology',
      'Gaming Consoles',
      'Smart Home Devices',
      'Drones',
      'Portable Speakers'
    ]
  },
  {
    id: 2,
    name: 'Clothing',
    subcategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Clothing",
      'Accessories',
      'Footwear',
      'Activewear',
      'Outerwear',
      'Swimwear',
      'Sleepwear',
      'Plus Size',
      'Maternity',
      'Uniforms'
    ]
  },
  {
    id: 3,
    name: 'Home & Kitchen',
    subcategories: [
      'Furniture',
      'Cookware',
      'Decor',
      'Appliances',
      'Bedding',
      'Storage Solutions',
      'Outdoor Furniture',
      'Lighting',
      'Garden Tools',
      'Cleaning Supplies',
      'Kitchen Storage',
      'Small Kitchen Appliances',
      'Barware'
    ]
  },
  {
    id: 4,
    name: 'Books',
    subcategories: [
      'Fiction',
      'Non-Fiction',
      'Educational',
      "Children's Books",
      'Comics & Graphic Novels',
      'Cookbooks',
      'Self-Help',
      'Biographies',
      'Science Fiction & Fantasy',
      'History',
      'Romance',
      'Travel',
      'Cookery'
    ]
  },
  {
    id: 5,
    name: 'Health & Beauty',
    subcategories: [
      'Skincare',
      'Haircare',
      'Personal Care',
      'Vitamins & Supplements',
      'Makeup',
      'Fragrances',
      'Fitness Equipment',
      'Oral Care',
      "Men's Grooming",
      'Body Care',
      'Hair Tools',
      'Health Monitors',
      'Wellness'
    ]
  },
  {
    id: 6,
    name: 'Toys & Games',
    subcategories: [
      'Action Figures',
      'Board Games',
      'Educational Toys',
      'Dolls',
      'Outdoor Play',
      'Building Toys',
      'Puzzles',
      'Pretend Play',
      'Remote Control',
      'Ride-Ons',
      'Arts & Crafts',
      'Electronic Toys',
      'STEM Toys'
    ]
  },
  {
    id: 7,
    name: 'Sports & Outdoors',
    subcategories: [
      'Camping & Hiking',
      'Fitness & Exercise',
      'Sports Equipment',
      'Cycling',
      'Fishing',
      'Water Sports',
      'Winter Sports',
      'Running',
      'Outdoor Furniture',
      'Sports Apparel',
      'Yoga & Pilates',
      'Climbing Gear',
      'Golf'
    ]
  },
  {
    id: 8,
    name: 'Automotive',
    subcategories: [
      'Car Electronics',
      'Interior Accessories',
      'Exterior Accessories',
      'Tools & Equipment',
      'Car Care',
      'Replacement Parts',
      'Motorcycles & ATVs',
      'Car Safety',
      'Auto Detailing',
      'Truck Accessories',
      'Car Covers',
      'Towing Equipment',
      'Car Lighting'
    ]
  },
  {
    id: 9,
    name: 'Office Supplies',
    subcategories: [
      'Furniture',
      'Stationery',
      'Printer Supplies',
      'Office Electronics',
      'Organization',
      'Office Décor',
      'Desks & Chairs',
      'Mailing Supplies',
      'Breakroom Supplies',
      'Calendars & Planners',
      'Filing & Storage',
      'Whiteboards',
      'Presentation Supplies'
    ]
  },
  {
    id: 10,
    name: 'Pet Supplies',
    subcategories: [
      'Dog Supplies',
      'Cat Supplies',
      'Bird Supplies',
      'Fish Supplies',
      'Small Animal Supplies',
      'Pet Furniture',
      'Pet Health',
      'Grooming',
      'Training & Behavior',
      'Pet Travel',
      'Aquarium Supplies',
      'Reptile Supplies',
      'Pet Apparel'
    ]
  },
  {
    id: 11,
    name: 'Garden & Outdoor',
    subcategories: [
      'Plants',
      'Garden Tools',
      'Outdoor Furniture',
      'Grills & Outdoor Cooking',
      'Planters & Pots',
      'Outdoor Lighting',
      'Fencing',
      'Gardening Supplies',
      'Outdoor Decor',
      'Landscaping',
      'Water Features',
      'Outdoor Heating',
      'Patio Furniture'
    ]
  },
  {
    id: 12,
    name: 'Jewelry & Watches',
    subcategories: [
      'Necklaces & Pendants',
      'Earrings',
      'Bracelets',
      'Rings',
      'Watches',
      'Brooches & Pins',
      "Men's Jewelry",
      'Jewelry Sets',
      'Jewelry Care & Storage',
      'Engagement & Wedding',
      'Luxury Watches',
      'Fashion Jewelry',
      'Custom Jewelry'
    ]
  },
  {
    id: 13,
    name: 'Arts & Crafts',
    subcategories: [
      'Drawing & Painting',
      'Craft Supplies',
      'Sewing & Knitting',
      'Beading & Jewelry Making',
      'Scrapbooking',
      'Model Building',
      'Art Supplies',
      'Fabric & Textiles',
      'Craft Kits',
      'Painting Tools',
      'DIY Projects',
      'Art Storage',
      'Craft Tools'
    ]
  },
  {
    id: 14,
    name: 'Musical Instruments',
    subcategories: [
      'Guitars',
      'Pianos & Keyboards',
      'Drums',
      'Orchestral Instruments',
      'Wind Instruments',
      'Electronic Instruments',
      'Recording Equipment',
      'Accessories',
      'Sheet Music',
      'Amplifiers',
      'Instrument Care',
      'Microphones',
      'DJ Equipment'
    ]
  },
  {
    id: 15,
    name: 'Baby Products',
    subcategories: [
      'Clothing',
      'Diapers & Wipes',
      'Feeding',
      'Nursery Furniture',
      'Toys',
      'Baby Gear',
      'Health & Safety',
      'Bedding',
      'Travel Gear',
      'Bath',
      'Car Seats',
      'Baby Monitors',
      'Swings & Bouncers'
    ]
  },
  {
    id: 16,
    name: 'Food & Beverage',
    subcategories: [
      'Snacks',
      'Beverages',
      'Groceries',
      'Gourmet Foods',
      'Health Foods',
      'Specialty Foods',
      'Organic',
      'Packaged Meals',
      'Baking Ingredients',
      'Condiments & Sauces',
      'Canned & Jarred Foods',
      'Frozen Foods',
      'Organic Produce'
    ]
  },
  {
    id: 17,
    name: 'Industrial & Scientific',
    subcategories: [
      'Lab Equipment',
      'Industrial Tools',
      'Safety Equipment',
      'Scientific Instruments',
      'Cleaning Supplies',
      'Office Supplies',
      'Material Handling',
      'Measuring & Testing',
      'HVAC',
      'Workplace Safety',
      'Construction Supplies',
      'Industrial Lighting',
      'Pumps & Valves'
    ]
  },
  {
    id: 18,
    name: 'Travel',
    subcategories: [
      'Luggage',
      'Travel Accessories',
      'Travel Clothing',
      'Outdoor Gear',
      'Travel Guides',
      'Electronics',
      'Travel Bags',
      'Travel Toiletries',
      'Camping Equipment',
      'Travel Health',
      'Travel Organizers',
      'Travel Security',
      'Travel Pillows'
    ]
  },
  {
    id: 19,
    name: 'Furniture',
    subcategories: [
      'Living Room Furniture',
      'Bedroom Furniture',
      'Office Furniture',
      'Outdoor Furniture',
      'Storage & Organization',
      'Dining Room Furniture',
      "Kids' Furniture",
      'Furniture Sets',
      'Mattresses',
      'Accent Furniture',
      'Home Office Furniture',
      'Furniture Accessories'
    ]
  },
  {
    id: 20,
    name: 'Hobbies',
    subcategories: [
      'Model Trains',
      'RC Vehicles',
      'Drones',
      'Collectibles',
      'Puzzles',
      'Board Games',
      'Craft Kits',
      'Hobby Tools',
      'Kits & Supplies',
      'Gardening',
      'Bird Watching',
      'Fishing'
    ]
  }
];
