export const roles = [
  'Mechanical Engineering Technician',
  'Electrical Engineering Technician',
  'Electronics Technician',
  'HVAC Technician (Heating, Ventilation, and Air Conditioning)',
  'Automotive Technician',
  'Aerospace Technician',
  'Civil Engineering Technician',
  'Industrial Engineering Technician',
  'Quality Control Technician',
  'Robotics Technician',
  'Maintenance Technician',
  'Instrumentation Technician',
  'CNC Technician (Computer Numerical Control)',
  'Telecommunications Technician',
  'Cable Technician',
  'Fiber Optic Technician',
  'RF Technician (Radio Frequency Technician)',
  'Satellite Technician',
  'Automotive Service Technician',
  'Diesel Technician',
  'Aviation Technician',
  'Marine Technician',
  'Motorcycle Technician',
  'Electrical Technician',
  'Wind Turbine Technician',
  'Solar Technician',
  'Power Plant Technician',
  'Gas Technician',
  'Water Treatment Technician',
  'Construction Technician',
  'Elevator Technician',
  'Building Maintenance Technician',
  'Plumbing Technician',
  'Carpentry Technician',
  'Audio/Visual Technician',
  'Broadcast Technician',
  'Sound Technician',
  'Lighting Technician',
  'Stage Technician',
  'Agricultural Technician',
  'Forestry Technician',
  'Environmental Field Technician',
  'Horticulture Technician',
  'Veterinary Technician',
  'Pest Control Technician',
  'Crime Scene Technician',
  'Nail Technician',
  'Esthetician Technician',
  'IT Support Technician',
  'Network Technician',
  'Help Desk Technician',
  'System Technician',
  'Hardware Technician',
  'Field Service Technician',
  'Data Center Technician',
  'Cybersecurity Technician'
];
