export const roles = [
  'Aerospace Technician',
  'Agricultural Technician',
  'Audio/Visual Technician',
  'Automotive Service Technician',
  'Automotive Technician',
  'Broadcast Technician',
  'Building Maintenance Technician',
  'Cable Technician',
  'Carpentry Technician',
  'Civil Engineering Technician',
  'CNC Technician (Computer Numerical Control)',
  'Construction Technician',
  'Crime Scene Technician',
  'Cybersecurity Technician',
  'Data Center Technician',
  'Diesel Technician',
  'Electrical Engineering Technician',
  'Electrical Technician',
  'Electronics Technician',
  'Elevator Technician',
  'Environmental Field Technician',
  'Esthetician Technician',
  'Fiber Optic Technician',
  'Field Service Technician',
  'Forestry Technician',
  'Gas Technician',
  'Help Desk Technician',
  'Horticulture Technician',
  'HVAC Technician (Heating, Ventilation, and Air Conditioning)',
  'Industrial Engineering Technician',
  'Instrumentation Technician',
  'IT Support Technician',
  'Lighting Technician',
  'Maintenance Technician',
  'Marine Technician',
  'Mechanical Engineering Technician',
  'Motorcycle Technician',
  'Nail Technician',
  'Network Technician',
  'Pest Control Technician',
  'Plumbing Technician',
  'Power Plant Technician',
  'Quality Control Technician',
  'RF Technician (Radio Frequency Technician)',
  'Robotics Technician',
  'Satellite Technician',
  'Solar Technician',
  'Sound Technician',
  'Stage Technician',
  'System Technician',
  'Telecommunications Technician',
  'Veterinary Technician',
  'Water Treatment Technician',
  'Wind Turbine Technician'
];
