export const techniciansData = [
  {
    id: 1,
    firstName: 'Michael',
    lastName: 'Ross',
    name: 'Michael Ross',
    email: 'mross@example.com',
    age: 41,
    gender: 'Male',
    role: 'Software Engineer',
    orders: 7641,
    progress: 67,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(541) 234-0987',
    country: 'United States',
    location: '2453 Cypress Avenue, San Francisco, USA - 94103',
    fatherName: 'Stephen Ross',
    about: 'Michael is a seasoned software engineer with a passion for backend development and cloud technologies.',
    avatar: 3,
    skills: ['Node.js', 'AWS', 'Docker', 'TypeScript', 'GraphQL'],
    time: ['3 days ago'],
    date: '02.08.2023'
  },
  {
    id: 2,
    firstName: 'Sarah',
    lastName: 'Lee',
    name: 'Sarah Lee',
    email: 'slee@example.com',
    age: 35,
    gender: 'Female',
    role: 'Marketing Manager',
    orders: 5432,
    progress: 58,
    status: 2,
    orderStatus: 'Shipped',
    contact: '(918) 333-7654',
    country: 'South Korea',
    location: '89 Hanul-ro, Seoul, South Korea - 11062',
    fatherName: 'James Lee',
    about: 'Sarah has over a decade of experience in digital marketing and brand management.',
    avatar: 7,
    skills: ['SEO', 'Content Marketing', 'Brand Strategy', 'Google Analytics'],
    time: ['2 weeks ago'],
    date: '20.07.2023'
  },
  {
    id: 3,
    firstName: 'Daniel',
    lastName: 'Martinez',
    name: 'Daniel Martinez',
    email: 'dmartinez@example.com',
    age: 29,
    gender: 'Male',
    role: 'Data Analyst',
    orders: 2356,
    progress: 34,
    status: 3,
    orderStatus: 'Processing',
    contact: '(650) 289-1245',
    country: 'Argentina',
    location: '4827 Belgrano Street, Buenos Aires, Argentina - 1425',
    fatherName: 'Carlos Martinez',
    about: 'Daniel specializes in big data analysis and works with various tools to derive business insights.',
    avatar: 1,
    skills: ['Python', 'SQL', 'Tableau', 'Power BI', 'R'],
    time: ['5 days ago'],
    date: '15.07.2023'
  },
  {
    id: 4,
    firstName: 'Jessica',
    lastName: 'Nguyen',
    name: 'Jessica Nguyen',
    email: 'jnguyen@example.com',
    age: 33,
    gender: 'Female',
    role: 'Product Manager',
    orders: 4398,
    progress: 80,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(303) 587-9081',
    country: 'Vietnam',
    location: '22 Le Duan Street, Ho Chi Minh City, Vietnam - 70000',
    fatherName: 'David Nguyen',
    about: 'Jessica is a dynamic product manager with a knack for leading cross-functional teams.',
    avatar: 6,
    skills: ['Agile', 'Scrum', 'Product Roadmap', 'Stakeholder Management'],
    time: ['1 month ago'],
    date: '30.06.2023'
  },
  {
    id: 5,
    firstName: 'Mohammed',
    lastName: 'Khan',
    name: 'Mohammed Khan',
    email: 'mkhan@example.com',
    age: 47,
    gender: 'Male',
    role: 'HR Specialist',
    orders: 5671,
    progress: 90,
    status: 2,
    orderStatus: 'Refunded',
    contact: '(917) 564-8902',
    country: 'United Arab Emirates',
    location: '1032 Sheikh Zayed Road, Dubai, UAE - 00000',
    fatherName: 'Ali Khan',
    about: 'Mohammed has extensive experience in talent acquisition and organizational development.',
    avatar: 5,
    skills: ['Recruitment', 'Employee Relations', 'Compensation & Benefits', 'Workplace Culture'],
    time: ['6 months ago'],
    date: '14.01.2023'
  },
  {
    id: 6,
    firstName: 'Elena',
    lastName: 'Garcia',
    name: 'Elena Garcia',
    email: 'egarcia@example.com',
    age: 50,
    gender: 'Female',
    role: 'Architect',
    orders: 721,
    progress: 12,
    status: 1,
    orderStatus: 'Shipped',
    contact: '(204) 564-1029',
    country: 'Spain',
    location: '195 La Rambla, Barcelona, Spain - 08001',
    fatherName: 'Pablo Garcia',
    about: 'Elena is an experienced architect focused on sustainable and innovative designs.',
    avatar: 4,
    skills: ['AutoCAD', 'Revit', 'Sustainable Design', 'Project Management'],
    time: ['4 hours ago'],
    date: '01.08.2023'
  },
  {
    id: 7,
    firstName: 'Lucas',
    lastName: 'Jenkins',
    name: 'Lucas Jenkins',
    email: 'ljenkins@example.com',
    age: 38,
    gender: 'Male',
    role: 'Financial Analyst',
    orders: 3654,
    progress: 73,
    status: 3,
    orderStatus: 'Processing',
    contact: '(701) 890-2345',
    country: 'Canada',
    location: '789 Maple Lane, Vancouver, Canada - V5K 1N2',
    fatherName: 'Robert Jenkins',
    about: 'Lucas excels in financial modeling and investment strategy.',
    avatar: 2,
    skills: ['Excel', 'Financial Modeling', 'Investment Analysis', 'Risk Management'],
    time: ['1 week ago'],
    date: '24.07.2023'
  },
  {
    id: 8,
    firstName: 'Sophia',
    lastName: 'Davis',
    name: 'Sophia Davis',
    email: 'sdavis@example.com',
    age: 31,
    gender: 'Female',
    role: 'Graphic Designer',
    orders: 8142,
    progress: 91,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(412) 765-9876',
    country: 'Australia',
    location: '142 Kingsway, Sydney, Australia - 2000',
    fatherName: 'John Davis',
    about: 'Sophia is a creative designer with a strong portfolio in brand identity and UI/UX design.',
    avatar: 7,
    skills: ['Photoshop', 'Illustrator', 'InDesign', 'Figma', 'Adobe XD'],
    time: ['2 days ago'],
    date: '03.08.2023'
  },
  {
    id: 9,
    firstName: 'Amir',
    lastName: 'Patel',
    name: 'Amir Patel',
    email: 'apatel@example.com',
    age: 45,
    gender: 'Male',
    role: 'Operations Manager',
    orders: 9321,
    progress: 85,
    status: 2,
    orderStatus: 'Shipped',
    contact: '(503) 234-6723',
    country: 'India',
    location: '19 Marine Drive, Mumbai, India - 400020',
    fatherName: 'Rajesh Patel',
    about: 'Amir is an operations manager with expertise in logistics and supply chain optimization.',
    avatar: 8,
    skills: ['Logistics', 'Supply Chain Management', 'Process Improvement', 'Lean Six Sigma'],
    time: ['3 weeks ago'],
    date: '15.07.2023'
  },
  {
    id: 10,
    firstName: 'Emma',
    lastName: 'Taylor',
    name: 'Emma Taylor',
    email: 'etaylor@example.com',
    age: 26,
    gender: 'Female',
    role: 'Customer Support Specialist',
    orders: 1204,
    progress: 29,
    status: 3,
    orderStatus: 'Processing',
    contact: '(646) 983-5632',
    country: 'United Kingdom',
    location: '78 High Street, London, UK - SW1A 1AA',
    fatherName: 'William Taylor',
    about: 'Emma is a dedicated customer support specialist who excels in resolving client issues.',
    avatar: 3,
    skills: ['CRM', 'Conflict Resolution', 'Customer Satisfaction', 'Technical Support'],
    time: ['3 hours ago'],
    date: '01.08.2023'
  },
  {
    id: 11,
    firstName: 'Oliver',
    lastName: 'Johnson',
    name: 'Oliver Johnson',
    email: 'ojohnson@example.com',
    age: 39,
    gender: 'Male',
    role: 'DevOps Engineer',
    orders: 5783,
    progress: 72,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(419) 562-9823',
    country: 'United States',
    location: '671 Lakeview Street, Denver, USA - 80202',
    fatherName: 'Benjamin Johnson',
    about: 'Oliver is a DevOps expert with a focus on cloud infrastructure and CI/CD pipelines.',
    avatar: 6,
    skills: ['AWS', 'Jenkins', 'Docker', 'Kubernetes'],
    time: ['1 day ago'],
    date: '04.08.2023'
  },
  {
    id: 12,
    firstName: 'Liam',
    lastName: 'Smith',
    name: 'Liam Smith',
    email: 'lsmith@example.com',
    age: 42,
    gender: 'Male',
    role: 'Project Manager',
    orders: 8932,
    progress: 89,
    status: 2,
    orderStatus: 'Shipped',
    contact: '(312) 763-0984',
    country: 'Canada',
    location: '234 Ridgeway Drive, Toronto, Canada - M5V 2T6',
    fatherName: 'Ethan Smith',
    about: 'Liam manages large-scale projects and specializes in agile methodologies.',
    avatar: 2,
    skills: ['Agile', 'Scrum', 'Kanban', 'Risk Management'],
    time: ['5 days ago'],
    date: '29.07.2023'
  },
  {
    id: 13,
    firstName: 'Ava',
    lastName: 'Wilson',
    name: 'Ava Wilson',
    email: 'awilson@example.com',
    age: 30,
    gender: 'Female',
    role: 'UX Designer',
    orders: 1029,
    progress: 66,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(914) 472-6781',
    country: 'United Kingdom',
    location: '45 Kensington Gardens, London, UK - W8 5TD',
    fatherName: 'George Wilson',
    about: 'Ava is a creative UX designer with a passion for improving user interactions.',
    avatar: 4,
    skills: ['Figma', 'Sketch', 'Wireframing', 'User Research'],
    time: ['3 weeks ago'],
    date: '17.07.2023'
  },
  {
    id: 14,
    firstName: 'Noah',
    lastName: 'Brown',
    name: 'Noah Brown',
    email: 'nbrown@example.com',
    age: 36,
    gender: 'Male',
    role: 'Business Analyst',
    orders: 6547,
    progress: 74,
    status: 2,
    orderStatus: 'Shipped',
    contact: '(701) 239-8543',
    country: 'Australia',
    location: '98 River Avenue, Melbourne, Australia - 3000',
    fatherName: 'Henry Brown',
    about: 'Noah provides key insights through data to help businesses make informed decisions.',
    avatar: 7,
    skills: ['SQL', 'Tableau', 'Business Intelligence', 'Excel'],
    time: ['2 months ago'],
    date: '05.06.2023'
  },
  {
    id: 15,
    firstName: 'Emily',
    lastName: 'Davis',
    name: 'Emily Davis',
    email: 'edavis@example.com',
    age: 28,
    gender: 'Female',
    role: 'HR Manager',
    orders: 4812,
    progress: 60,
    status: 3,
    orderStatus: 'Processing',
    contact: '(413) 578-9123',
    country: 'New Zealand',
    location: '17 Island Street, Wellington, New Zealand - 6011',
    fatherName: 'Jacob Davis',
    about: 'Emily excels at employee engagement and talent management strategies.',
    avatar: 5,
    skills: ['Recruitment', 'Employee Engagement', 'Conflict Resolution', 'Performance Management'],
    time: ['1 week ago'],
    date: '26.07.2023'
  },
  {
    id: 16,
    firstName: 'William',
    lastName: 'Clark',
    name: 'William Clark',
    email: 'wclark@example.com',
    age: 52,
    gender: 'Male',
    role: 'CTO',
    orders: 18945,
    progress: 95,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(520) 901-2456',
    country: 'United States',
    location: '1242 High Street, Boston, USA - 02115',
    fatherName: 'Thomas Clark',
    about: 'William is the CTO at a Fortune 500 company with extensive knowledge of system architectures.',
    avatar: 3,
    skills: ['Leadership', 'Enterprise Architecture', 'Cloud Computing', 'Strategic Planning'],
    time: ['6 months ago'],
    date: '15.02.2023'
  },
  {
    id: 17,
    firstName: 'Grace',
    lastName: 'Morris',
    name: 'Grace Morris',
    email: 'gmorris@example.com',
    age: 24,
    gender: 'Female',
    role: 'Social Media Manager',
    orders: 2731,
    progress: 52,
    status: 3,
    orderStatus: 'Processing',
    contact: '(567) 890-2345',
    country: 'United Kingdom',
    location: '89 St. Peter’s Street, Manchester, UK - M1 4WQ',
    fatherName: 'Edward Morris',
    about: 'Grace manages multiple social media platforms and specializes in content creation.',
    avatar: 8,
    skills: ['Social Media Marketing', 'Content Strategy', 'Analytics', 'Copywriting'],
    time: ['3 weeks ago'],
    date: '12.07.2023'
  },
  {
    id: 18,
    firstName: 'James',
    lastName: 'Evans',
    name: 'James Evans',
    email: 'jevans@example.com',
    age: 44,
    gender: 'Male',
    role: 'Cybersecurity Analyst',
    orders: 3214,
    progress: 68,
    status: 2,
    orderStatus: 'Shipped',
    contact: '(321) 908-7643',
    country: 'South Africa',
    location: '23 Nelson Mandela Drive, Johannesburg, South Africa - 2001',
    fatherName: 'Andrew Evans',
    about: 'James is an experienced cybersecurity analyst specializing in network protection and risk assessment.',
    avatar: 1,
    skills: ['Network Security', 'Penetration Testing', 'Incident Response', 'Risk Management'],
    time: ['1 month ago'],
    date: '04.07.2023'
  },
  {
    id: 19,
    firstName: 'Ella',
    lastName: 'Scott',
    name: 'Ella Scott',
    email: 'escott@example.com',
    age: 27,
    gender: 'Female',
    role: 'Content Writer',
    orders: 1954,
    progress: 33,
    status: 3,
    orderStatus: 'Processing',
    contact: '(778) 645-0193',
    country: 'Ireland',
    location: '12 Moore Street, Dublin, Ireland - D02 FY42',
    fatherName: 'Patrick Scott',
    about: 'Ella is a creative content writer with expertise in SEO and digital storytelling.',
    avatar: 6,
    skills: ['SEO Writing', 'Content Strategy', 'Copywriting', 'Blogging'],
    time: ['2 weeks ago'],
    date: '19.07.2023'
  },
  {
    id: 20,
    firstName: 'Henry',
    lastName: 'Wright',
    name: 'Henry Wright',
    email: 'hwright@example.com',
    age: 33,
    gender: 'Male',
    role: 'Legal Advisor',
    orders: 7123,
    progress: 79,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(213) 490-3456',
    country: 'United States',
    location: '554 Lexington Avenue, New York, USA - 10022',
    fatherName: 'Richard Wright',
    about: 'Henry is a legal advisor specializing in corporate law and compliance.',
    avatar: 3,
    skills: ['Corporate Law', 'Contracts', 'Compliance', 'Litigation'],
    time: ['5 days ago'],
    date: '31.07.2023'
  },
  {
    id: 21,
    firstName: 'Mia',
    lastName: 'Campbell',
    name: 'Mia Campbell',
    email: 'mcampbell@example.com',
    age: 40,
    gender: 'Female',
    role: 'Data Scientist',
    orders: 9435,
    progress: 92,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(619) 678-1324',
    country: 'Germany',
    location: '14 Kurfürstendamm, Berlin, Germany - 10719',
    fatherName: 'Paul Campbell',
    about: 'Mia is an accomplished data scientist who applies machine learning techniques to solve business problems.',
    avatar: 7,
    skills: ['Python', 'Machine Learning', 'Statistics', 'Data Visualization'],
    time: ['2 months ago'],
    date: '13.06.2023'
  },
  {
    id: 22,
    firstName: 'Sophia',
    lastName: 'Mitchell',
    name: 'Sophia Mitchell',
    email: 'smitchell@example.com',
    age: 34,
    gender: 'Female',
    role: 'Marketing Strategist',
    orders: 3851,
    progress: 49,
    status: 2,
    orderStatus: 'Shipped',
    contact: '(403) 235-8741',
    country: 'Canada',
    location: '234 Lakeview Crescent, Calgary, Canada - T2N 1N4',
    fatherName: 'Samuel Mitchell',
    about: 'Sophia develops marketing strategies for product launches and digital campaigns.',
    avatar: 2,
    skills: ['Digital Marketing', 'Campaign Management', 'Market Research', 'SEO'],
    time: ['4 weeks ago'],
    date: '08.07.2023'
  },
  {
    id: 23,
    firstName: 'Elijah',
    lastName: 'Perez',
    name: 'Elijah Perez',
    email: 'eperez@example.com',
    age: 29,
    gender: 'Male',
    role: 'Cloud Architect',
    orders: 5734,
    progress: 81,
    status: 1,
    orderStatus: 'Delivered',
    contact: '(915) 463-8234',
    country: 'Mexico',
    location: '567 Av. Revolución, Mexico City, Mexico - 03100',
    fatherName: 'Carlos Perez',
    about: 'Elijah is a cloud architect specializing in serverless applications and scalable systems.',
    avatar: 5,
    skills: ['AWS', 'Azure', 'Microservices', 'Cloud Security'],
    time: ['3 months ago'],
    date: '02.06.2023'
  },
  {
    id: 24,
    firstName: 'Isabella',
    lastName: 'Garcia',
    name: 'Isabella Garcia',
    email: 'igarcia@example.com',
    age: 22,
    gender: 'Female',
    role: 'Intern',
    orders: 931,
    progress: 23,
    status: 3,
    orderStatus: 'Processing',
    contact: '(702) 234-8790',
    country: 'United States',
    location: '123 Elm Street, Los Angeles, USA - 90012',
    fatherName: 'David Garcia',
    about: 'Isabella is a recent graduate interning in software development.',
    avatar: 1,
    skills: ['JavaScript', 'React', 'HTML', 'CSS'],
    time: ['1 week ago'],
    date: '25.07.2023'
  },
  {
    id: 25,
    firstName: 'Lucas',
    lastName: 'Martin',
    name: 'Lucas Martin',
    email: 'lmartin@example.com',
    age: 38,
    gender: 'Male',
    role: 'Product Manager',
    orders: 6421,
    progress: 77,
    status: 2,
    orderStatus: 'Shipped',
    contact: '(314) 765-0987',
    country: 'France',
    location: '56 Rue de Rivoli, Paris, France - 75004',
    fatherName: 'Robert Martin',
    about: 'Lucas is a product manager leading cross-functional teams to deliver software solutions.',
    avatar: 4,
    skills: ['Product Management', 'Scrum', 'Agile', 'Leadership'],
    time: ['2 weeks ago'],
    date: '19.07.2023'
  }
];
